volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/sflechel/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/sflechel/data/wordpress

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - docker_network
    restart: on-failure
    healthcheck: 
      test: ["CMD", "mariadb-admin", "ping", "--skip-ssl", "--host=localhost", "--user=root"]
      interval: 5s
      retries: 10

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_volume:/var/www
    depends_on:
      - mariadb
    networks:
      - docker_network
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www
    networks:
      - docker_network
    restart: on-failure

networks:
  docker_network:
    driver: bridge
